const express = require('express');
const cors = require('cors');
const bcrypt = require('bcryptjs');
const jwt = require('jsonwebtoken');
const multer = require('multer');
const fs = require('node:fs');
const path = require('node:path');
const { DatabaseSync } = require('node:sqlite');

const root = path.resolve(__dirname, '..');
for (const envFile of ['.env', '.env.example']) {
  const envPath = path.join(root, envFile);
  if (!fs.existsSync(envPath)) continue;
  for (const line of fs.readFileSync(envPath, 'utf8').split(/\r?\n/)) {
    const match = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*?)\s*$/);
    if (match && !process.env[match[1]]) process.env[match[1]] = match[2];
  }
  if (envFile === '.env') break;
}
const port = Number(process.env.PORT || 8787);
const jwtSecret = process.env.JWT_SECRET || 'development-only-change-me';
const databasePath = path.resolve(root, process.env.DATABASE_PATH || 'server/data/catalog.sqlite');
const uploadDirectory = path.resolve(root, process.env.UPLOAD_DIR || 'server/uploads');
fs.mkdirSync(path.dirname(databasePath), { recursive: true });
fs.mkdirSync(uploadDirectory, { recursive: true });
const db = new DatabaseSync(databasePath);
db.exec(fs.readFileSync(path.join(__dirname, 'schema.sql'), 'utf8'));
const now = () => new Date().toISOString();
const slugify = (value) => value.toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
const safeJson = (value, fallback) => { try { return JSON.parse(value); } catch { return fallback; } };
const mapCategory = (row) => ({ ...row, parentId: row.parent_id, image: row.image_url, active: row.status === 'ACTIVE', order: row.sort_order });
const mapBrand = (row) => ({ ...row, logoUrl: row.logo_url, active: row.status === 'ACTIVE' });
const mapProductType = (row) => ({ ...row, categoryId: row.category_id, active: row.status === 'ACTIVE' });
const mapAttribute = (row) => ({ ...row, categoryId: row.category_id, options: safeJson(row.options_json, []), required: Boolean(row.required), filterable: Boolean(row.filterable), searchable: Boolean(row.searchable), active: row.status === 'ACTIVE' });
const mapProduct = (row) => ({ ...row, categoryId: row.category_id, code: row.sku, category: row.category_name, brand: row.brand_name || '', image: row.image_url || '', attributes: safeJson(row.attributes_json, {}), status: row.status === 'ACTIVE' ? 'Active' : 'Inactive' });
const productSelect = `SELECT p.*, c.name category_name, b.name brand_name FROM products p JOIN categories c ON c.id = p.category_id LEFT JOIN brands b ON b.id = p.brand_id`;
function seed() {
  const adminEmail = process.env.ADMIN_EMAIL || 'owner@murugesan.in';
  const configuredPassword = process.env.ADMIN_PASSWORD || 'change-this-before-production';
  const existingAdmin = db.prepare('SELECT id FROM users WHERE email = ?').get(adminEmail);
  if (!existingAdmin) {
    const timestamp = now();
    db.prepare('INSERT INTO users (name,email,password_hash,role,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?)').run('Store Owner', adminEmail, bcrypt.hashSync(configuredPassword, 12), 'ADMIN', 'ACTIVE', timestamp, timestamp);
  } else if (process.env.ADMIN_PASSWORD) {
    db.prepare('UPDATE users SET password_hash = ?, updated_at = ? WHERE id = ?').run(bcrypt.hashSync(configuredPassword, 12), now(), existingAdmin.id);
  }
  if (db.prepare('SELECT COUNT(*) count FROM categories').get().count > 0) return;
  const categoryNames = ['Electrical Switches', 'Sockets', 'Wires & Cables', 'Lighting', 'Fan Regulators', 'Electrical Accessories', 'Tools', 'Hardware', 'Plumbing Accessories', 'Other Products'];
  const categoryIds = new Map();
  const categoryInsert = db.prepare('INSERT INTO categories (name,slug,description,sort_order,created_at,updated_at) VALUES (?,?,?,?,?,?)');
  const timestamp = now();
  for (const [index, name] of categoryNames.entries()) categoryIds.set(name, Number(categoryInsert.run(name, slugify(name), 'Reliable products for everyday work.', index + 1, timestamp, timestamp).lastInsertRowid));
  const brandInsert = db.prepare('INSERT INTO brands (name,slug,created_at,updated_at) VALUES (?,?,?,?)');
  const anchor = Number(brandInsert.run('Anchor', 'anchor', timestamp, timestamp).lastInsertRowid);
  const products = [
    ['1401', '10A Bell Push', 'Electrical Switches', anchor, 95, 120, 42, 'Compact bell push for residential and commercial use.', '10A / Modular / White finish'],
    ['1402', '10A 2 Way Switch', 'Electrical Switches', anchor, 120, 145, 50, 'Durable modular switch for everyday electrical work.', '10A / 2-way / Modular'],
    ['US-10', 'Universal Socket', 'Sockets', null, 250, 290, 24, 'Safe, compact universal socket with a clean finish.', '6A-16A / Universal / Modular'],
    ['FR-05', 'Fan Regulator', 'Fan Regulators', null, 320, 375, 8, 'Smooth speed control for ceiling and wall fans.', '5-step / Silent operation'],
    ['FL-03', 'LED Foot Light', 'Lighting', null, 180, 225, 0, 'Warm, efficient accent light for steps and passages.', '3W / Warm white / LED'],
    ['BH-650-ID', 'Impact Drill 650W', 'Tools', null, 3290, 3999, 6, 'Jobsite-ready impact drill with a 13mm chuck.', '650W / 13mm chuck'],
  ];
  const productInsert = db.prepare('INSERT INTO products (sku,name,slug,category_id,brand_id,description,details,price,mrp,stock,image_url,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)');
  for (const [sku, name, category, brandId, price, mrp, stock, description, details] of products) productInsert.run(sku, name, `${slugify(name)}-${sku.toLowerCase()}`, categoryIds.get(category), brandId, description, details, price, mrp, stock, null, timestamp, timestamp);
}
seed();
const app = express();
app.use(cors());
app.use(express.json({ limit: '2mb' }));
app.use('/uploads', express.static(uploadDirectory));
const upload = multer({ dest: uploadDirectory, limits: { fileSize: 10 * 1024 * 1024 } });
const resetCodes = new Map();
const auth = (req, res, next) => { const token = (req.headers.authorization || '').replace(/^Bearer /, ''); try { req.user = jwt.verify(token, jwtSecret); next(); } catch { res.status(401).json({ error: 'Authentication required' }); } };
const admin = (req, res, next) => req.user?.role === 'ADMIN' ? next() : res.status(403).json({ error: 'Admin permission required' });
app.get('/api/health', (_req, res) => res.json({ ok: true, database: 'sqlite' }));
app.post('/api/auth/login', (req, res) => { const email = String(req.body.email || '').trim().toLowerCase(); const password = String(req.body.password || ''); const user = db.prepare('SELECT * FROM users WHERE email = ? AND status = ?').get(email, 'ACTIVE'); if (!user || !bcrypt.compareSync(password, user.password_hash)) return res.status(401).json({ error: 'Invalid email or password' }); const token = jwt.sign({ id: user.id, role: user.role, email: user.email }, jwtSecret, { expiresIn: '8h' }); res.json({ token, user: { id: user.id, name: user.name, email: user.email, role: user.role } }); });
app.post('/api/auth/forgot-password', (req, res) => { const email = String(req.body.email || '').trim(); const user = db.prepare('SELECT id FROM users WHERE email = ? AND status = ?').get(email, 'ACTIVE'); const response = { message: 'If that account exists, password reset instructions have been generated.' }; if (user && process.env.NODE_ENV !== 'production') { const code = String(Math.floor(100000 + Math.random() * 900000)); resetCodes.set(email.toLowerCase(), { code, expiresAt: Date.now() + 15 * 60 * 1000 }); response.resetCode = code; } res.json(response); });
app.post('/api/auth/reset-password', (req, res) => { const email = String(req.body.email || '').trim().toLowerCase(); const code = String(req.body.code || ''); const password = String(req.body.password || ''); const reset = resetCodes.get(email); if (!reset || reset.code !== code || reset.expiresAt < Date.now()) return res.status(400).json({ error: 'Invalid or expired reset code' }); if (password.length < 8) return res.status(400).json({ error: 'Password must be at least 8 characters' }); db.prepare('UPDATE users SET password_hash = ?, updated_at = ? WHERE email = ?').run(bcrypt.hashSync(password, 12), now(), email); resetCodes.delete(email); res.json({ message: 'Password reset successfully' }); });
app.get('/api/catalog', (_req, res) => { const categories = db.prepare("SELECT * FROM categories WHERE status = 'ACTIVE' ORDER BY sort_order, name").all().map(mapCategory); const products = db.prepare(`${productSelect} WHERE p.status = 'ACTIVE' ORDER BY p.created_at DESC`).all().map(mapProduct); res.json({ categories, products }); });
app.get('/api/categories', (_req, res) => res.json(db.prepare('SELECT * FROM categories ORDER BY sort_order, name').all().map(mapCategory)));
app.post('/api/categories', auth, admin, (req, res) => { const body = req.body || {}; const timestamp = now(); try { const result = db.prepare('INSERT INTO categories (name,slug,parent_id,image_url,description,status,sort_order,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?)').run(String(body.name).trim(), slugify(body.slug || body.name), body.parentId || null, body.imageUrl || null, body.description || '', body.status || 'ACTIVE', Number(body.sortOrder || 0), timestamp, timestamp); res.status(201).json(mapCategory(db.prepare('SELECT * FROM categories WHERE id = ?').get(result.lastInsertRowid))); } catch (error) { res.status(400).json({ error: error.message.includes('UNIQUE') ? 'Category slug already exists' : 'Unable to create category' }); } });
app.patch('/api/categories/:id', auth, admin, (req, res) => { const body = req.body || {}; const timestamp = now(); try { const result = db.prepare('UPDATE categories SET name = COALESCE(?, name), slug = COALESCE(?, slug), parent_id = ?, image_url = ?, description = COALESCE(?, description), status = COALESCE(?, status), sort_order = COALESCE(?, sort_order), updated_at = ? WHERE id = ?').run(body.name == null ? null : String(body.name).trim(), body.slug == null ? null : slugify(body.slug || body.name), body.parentId ?? null, body.imageUrl ?? null, body.description == null ? null : String(body.description), body.status == null ? null : body.status, body.sortOrder == null ? null : Number(body.sortOrder), timestamp, Number(req.params.id)); if (!result.changes) return res.status(404).json({ error: 'Category not found' }); res.json(mapCategory(db.prepare('SELECT * FROM categories WHERE id = ?').get(Number(req.params.id)))); } catch (error) { res.status(400).json({ error: error.message.includes('UNIQUE') ? 'Category slug already exists' : 'Unable to update category' }); } });
app.patch('/api/categories/:id/archive', auth, admin, (req, res) => { const id = Number(req.params.id); const productCount = db.prepare("SELECT COUNT(*) count FROM products WHERE category_id = ? AND status != 'ARCHIVED'").get(id).count; if (productCount > 0) { const result = db.prepare("UPDATE categories SET status = 'ARCHIVED', updated_at = ? WHERE id = ?").run(now(), id); if (!result.changes) return res.status(404).json({ error: 'Category not found' }); return res.json({ archived: true, productCount, message: 'Category archived and removed from the public catalog.' }); } const result = db.prepare('DELETE FROM categories WHERE id = ?').run(id); if (!result.changes) return res.status(404).json({ error: 'Category not found' }); res.json({ deleted: true, message: 'Category deleted because it has no remaining products.' }); });
app.patch('/api/categories/:id/restore', auth, admin, (req, res) => { const result = db.prepare("UPDATE categories SET status = 'ACTIVE', updated_at = ? WHERE id = ?").run(now(), Number(req.params.id)); if (!result.changes) return res.status(404).json({ error: 'Category not found' }); res.json({ restored: true }); });
app.get('/api/brands', (_req, res) => res.json(db.prepare('SELECT * FROM brands ORDER BY name').all().map(mapBrand)));
app.post('/api/brands', auth, admin, (req, res) => { const body = req.body || {}; const timestamp = now(); try { const result = db.prepare('INSERT INTO brands (name,slug,logo_url,description,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?)').run(String(body.name).trim(), slugify(body.slug || body.name), body.logoUrl || null, body.description || '', body.status || 'ACTIVE', timestamp, timestamp); res.status(201).json(mapBrand(db.prepare('SELECT * FROM brands WHERE id = ?').get(result.lastInsertRowid))); } catch (error) { res.status(400).json({ error: error.message.includes('UNIQUE') ? 'Brand slug already exists' : 'Unable to create brand' }); } });
app.patch('/api/brands/:id', auth, admin, (req, res) => { const body = req.body || {}; const timestamp = now(); try { const result = db.prepare('UPDATE brands SET name = COALESCE(?, name), logo_url = COALESCE(?, logo_url), description = COALESCE(?, description), status = COALESCE(?, status), updated_at = ? WHERE id = ?').run(body.name ?? null, body.logoUrl ?? null, body.description ?? null, body.status ?? null, timestamp, Number(req.params.id)); if (!result.changes) return res.status(404).json({ error: 'Brand not found' }); res.json(mapBrand(db.prepare('SELECT * FROM brands WHERE id = ?').get(Number(req.params.id)))); } catch { res.status(400).json({ error: 'Unable to update brand' }); } });
app.patch('/api/brands/:id/archive', auth, admin, (req, res) => { const id = Number(req.params.id); const productCount = db.prepare("SELECT COUNT(*) count FROM products WHERE brand_id = ? AND status != 'ARCHIVED'").get(id).count; if (productCount > 0) { const result = db.prepare("UPDATE brands SET status = 'ARCHIVED', updated_at = ? WHERE id = ?").run(now(), id); if (!result.changes) return res.status(404).json({ error: 'Brand not found' }); return res.json({ archived: true, productCount, message: 'Brand archived and removed from active catalog listings.' }); } const result = db.prepare('DELETE FROM brands WHERE id = ?').run(id); if (!result.changes) return res.status(404).json({ error: 'Brand not found' }); res.json({ deleted: true, message: 'Brand deleted because it has no remaining products.' }); });
app.patch('/api/brands/:id/restore', auth, admin, (req, res) => { const result = db.prepare("UPDATE brands SET status = 'ACTIVE', updated_at = ? WHERE id = ?").run(now(), Number(req.params.id)); if (!result.changes) return res.status(404).json({ error: 'Brand not found' }); res.json({ restored: true }); });
app.get('/api/product-types', (_req, res) => { const categoryId = Number(req.query.categoryId || 0); const query = categoryId ? 'SELECT * FROM product_types WHERE category_id = ? ORDER BY sort_order, name' : 'SELECT * FROM product_types ORDER BY category_id, sort_order, name'; const rows = categoryId ? db.prepare(query).all(categoryId) : db.prepare(query).all(); res.json(rows.map(mapProductType)); });
app.post('/api/product-types', auth, admin, (req, res) => { const body = req.body || {}; const timestamp = now(); try { const result = db.prepare('INSERT INTO product_types (category_id,name,status,sort_order,created_at,updated_at) VALUES (?,?,?,?,?,?)').run(Number(body.categoryId), String(body.name).trim(), body.status || 'ACTIVE', Number(body.sortOrder || 0), timestamp, timestamp); res.status(201).json(mapProductType(db.prepare('SELECT * FROM product_types WHERE id = ?').get(result.lastInsertRowid))); } catch (error) { res.status(400).json({ error: error.message.includes('UNIQUE') ? 'A product type with that name already exists in this category' : 'Unable to create product type' }); } });
app.patch('/api/product-types/:id/archive', auth, admin, (req, res) => { const id = Number(req.params.id); const productCount = db.prepare("SELECT COUNT(*) count FROM products WHERE product_type_id = ? AND status != 'ARCHIVED'").get(id).count; if (productCount > 0) { const result = db.prepare("UPDATE product_types SET status = 'ARCHIVED', updated_at = ? WHERE id = ?").run(now(), id); if (!result.changes) return res.status(404).json({ error: 'Product type not found' }); return res.json({ archived: true, productCount, message: 'Product type archived and removed from active category workflows.' }); } const result = db.prepare('DELETE FROM product_types WHERE id = ?').run(id); if (!result.changes) return res.status(404).json({ error: 'Product type not found' }); res.json({ deleted: true, message: 'Product type deleted because it has no remaining products.' }); });
app.patch('/api/product-types/:id/restore', auth, admin, (req, res) => { const result = db.prepare("UPDATE product_types SET status = 'ACTIVE', updated_at = ? WHERE id = ?").run(now(), Number(req.params.id)); if (!result.changes) return res.status(404).json({ error: 'Product type not found' }); res.json({ restored: true }); });
app.get('/api/attributes', (_req, res) => { const categoryId = Number(req.query.categoryId || 0); const query = categoryId ? 'SELECT * FROM attributes WHERE category_id = ? ORDER BY sort_order, name' : 'SELECT * FROM attributes ORDER BY category_id, sort_order, name'; const rows = categoryId ? db.prepare(query).all(categoryId) : db.prepare(query).all(); res.json(rows.map(mapAttribute)); });
app.post('/api/attributes', auth, admin, (req, res) => { const body = req.body || {}; const timestamp = now(); try { const result = db.prepare('INSERT INTO attributes (category_id,name,type,required,filterable,searchable,options_json,status,sort_order,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)').run(Number(body.categoryId), String(body.name).trim(), String(body.type || 'Text'), Number(Boolean(body.required)), Number(Boolean(body.filterable)), Number(Boolean(body.searchable)), JSON.stringify(Array.isArray(body.options) ? body.options : []), body.status || 'ACTIVE', Number(body.sortOrder || 0), timestamp, timestamp); res.status(201).json(mapAttribute(db.prepare('SELECT * FROM attributes WHERE id = ?').get(result.lastInsertRowid))); } catch (error) { res.status(400).json({ error: error.message.includes('UNIQUE') ? 'An attribute with that name already exists in this category' : 'Unable to create attribute' }); } });
app.patch('/api/attributes/:id/archive', auth, admin, (req, res) => { const id = Number(req.params.id); const productCount = db.prepare("SELECT COUNT(*) count FROM products WHERE attributes_json LIKE ? AND status != 'ARCHIVED'").get(`%"${id}"%`).count; if (productCount > 0) { const result = db.prepare("UPDATE attributes SET status = 'ARCHIVED', updated_at = ? WHERE id = ?").run(now(), id); if (!result.changes) return res.status(404).json({ error: 'Attribute not found' }); return res.json({ archived: true, productCount, message: 'Attribute archived and preserved on existing products.' }); } const result = db.prepare('DELETE FROM attributes WHERE id = ?').run(id); if (!result.changes) return res.status(404).json({ error: 'Attribute not found' }); res.json({ deleted: true, message: 'Attribute deleted because it is not used by any products.' }); });
app.patch('/api/attributes/:id/restore', auth, admin, (req, res) => { const result = db.prepare("UPDATE attributes SET status = 'ACTIVE', updated_at = ? WHERE id = ?").run(now(), Number(req.params.id)); if (!result.changes) return res.status(404).json({ error: 'Attribute not found' }); res.json({ restored: true }); });
app.post('/api/migration/legacy', auth, admin, (req, res) => { const categories = Array.isArray(req.body?.categories) ? req.body.categories : []; const products = Array.isArray(req.body?.products) ? req.body.products : []; const timestamp = now(); try { db.exec('BEGIN'); const categoryInsert = db.prepare('INSERT OR IGNORE INTO categories (name,slug,description,sort_order,created_at,updated_at) VALUES (?,?,?,?,?,?)'); for (const [index, category] of categories.entries()) categoryInsert.run(String(category.name || '').trim(), slugify(category.slug || category.name || `legacy-${index}`), category.description || '', Number(category.order || index + 1), timestamp, timestamp); const categoryId = db.prepare('SELECT id FROM categories WHERE name = ? COLLATE NOCASE'); const brandInsert = db.prepare('INSERT OR IGNORE INTO brands (name,slug,created_at,updated_at) VALUES (?,?,?,?)'); const brandId = db.prepare('SELECT id FROM brands WHERE name = ? COLLATE NOCASE'); const productInsert = db.prepare('INSERT OR IGNORE INTO products (sku,name,slug,category_id,brand_id,description,details,price,mrp,stock,unit,image_url,attributes_json,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)'); for (const product of products) { const categoryRow = categoryId.get(String(product.category || 'Other Products')); if (!categoryRow) continue; const brandName = String(product.brand || '').trim(); if (brandName) brandInsert.run(brandName, slugify(brandName), timestamp, timestamp); const brandRow = brandName ? brandId.get(brandName) : null; const sku = String(product.code || product.sku || '').trim(); if (!sku) continue; productInsert.run(sku, String(product.name || sku), slugify(`${product.name || sku}-${sku}`), categoryRow.id, brandRow?.id || null, product.description || '', product.details || '', Number(product.price || 0), Number(product.mrp || product.price || 0), Number(product.stock || 0), product.unit || 'Nos', product.image || null, JSON.stringify(product.attributes || {}), timestamp, timestamp); } db.exec('COMMIT'); res.json({ migrated: { categories: categories.length, products: products.length } }); } catch (error) { db.exec('ROLLBACK'); res.status(400).json({ error: 'Migration failed', detail: error.message }); } });
app.get('/api/products', (req, res) => { const page = Math.max(1, Number(req.query.page || 1)); const limit = Math.min(100, Math.max(1, Number(req.query.limit || 50))); const search = String(req.query.search || '').trim(); const params = []; const filters = ["p.status = 'ACTIVE'"]; if (search) { filters.push('(p.name LIKE ? OR p.sku LIKE ? OR c.name LIKE ? OR b.name LIKE ?)'); params.push(`%${search}%`, `%${search}%`, `%${search}%`, `%${search}%`); } if (req.query.categoryId) { filters.push('p.category_id = ?'); params.push(Number(req.query.categoryId)); } const where = ` WHERE ${filters.join(' AND ')}`; const total = db.prepare(`SELECT COUNT(*) count FROM products p JOIN categories c ON c.id = p.category_id LEFT JOIN brands b ON b.id = p.brand_id${where}`).get(...params).count; const rows = db.prepare(`${productSelect}${where} ORDER BY p.created_at DESC LIMIT ? OFFSET ?`).all(...params, limit, (page - 1) * limit).map(mapProduct); res.json({ data: rows, page, limit, total, pages: Math.ceil(total / limit) }); });
app.post('/api/products', auth, admin, (req, res) => { const body = req.body || {}; if (!body.sku || !body.name || !body.categoryId) return res.status(400).json({ error: 'SKU, product name and category are required' }); const timestamp = now(); try { const result = db.prepare('INSERT INTO products (sku,name,slug,category_id,brand_id,product_type_id,description,details,price,mrp,discount,stock,unit,image_url,image_urls_json,attributes_json,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(body.sku.trim(), body.name.trim(), slugify(`${body.name}-${body.sku}`), Number(body.categoryId), body.brandId || null, body.productTypeId || null, body.description || '', body.details || '', Number(body.price || 0), Number(body.mrp || body.price || 0), Number(body.discount || 0), Number(body.stock || 0), body.unit || 'Nos', body.imageUrl || null, JSON.stringify(body.imageUrls || []), JSON.stringify(body.attributes || {}), body.status || 'ACTIVE', timestamp, timestamp); res.status(201).json(mapProduct(db.prepare(`${productSelect} WHERE p.id = ?`).get(result.lastInsertRowid))); } catch (error) { res.status(error.message.includes('UNIQUE') ? 409 : 400).json({ error: error.message.includes('UNIQUE') ? 'SKU already exists' : 'Unable to create product' }); } });
app.patch('/api/products/:id', auth, admin, (req, res) => { const body = req.body || {}; const timestamp = now(); try { const result = db.prepare('UPDATE products SET name = COALESCE(?, name), description = COALESCE(?, description), details = COALESCE(?, details), price = COALESCE(?, price), mrp = COALESCE(?, mrp), discount = COALESCE(?, discount), stock = COALESCE(?, stock), unit = COALESCE(?, unit), status = COALESCE(?, status), updated_at = ? WHERE id = ?').run(body.name ?? null, body.description ?? null, body.details ?? null, body.price ?? null, body.mrp ?? null, body.discount ?? null, body.stock ?? null, body.unit ?? null, body.status ?? null, timestamp, Number(req.params.id)); if (!result.changes) return res.status(404).json({ error: 'Product not found' }); res.json(mapProduct(db.prepare(`${productSelect} WHERE p.id = ?`).get(Number(req.params.id)))); } catch { res.status(400).json({ error: 'Unable to update product' }); } });
app.patch('/api/products/:id/archive', auth, admin, (req, res) => { const result = db.prepare("UPDATE products SET status = 'ARCHIVED', updated_at = ? WHERE id = ?").run(now(), Number(req.params.id)); if (!result.changes) return res.status(404).json({ error: 'Product not found' }); res.status(204).end(); });
app.post('/api/images', auth, admin, upload.single('image'), (req, res) => { if (!req.file) return res.status(400).json({ error: 'Image is required' }); const extension = path.extname(req.file.originalname).toLowerCase() || '.bin'; const target = `${req.file.path}${extension}`; fs.renameSync(req.file.path, target); res.status(201).json({ url: `/uploads/${path.basename(target)}` }); });
app.get('/api/admin/stats', auth, admin, (_req, res) => { const count = (sql) => db.prepare(sql).get().count; res.json({ products: count("SELECT COUNT(*) count FROM products WHERE status != 'ARCHIVED'"), categories: count("SELECT COUNT(*) count FROM categories WHERE status != 'ARCHIVED'"), brands: count("SELECT COUNT(*) count FROM brands WHERE status != 'ARCHIVED'"), customers: count("SELECT COUNT(*) count FROM users WHERE role = 'CUSTOMER'") }); });
app.use((error, _req, res, _next) => { console.error(error); res.status(500).json({ error: 'Unexpected server error' }); });
app.listen(port, () => console.log(`Catalog API listening on http://localhost:${port}`));
